version: "2.3"

services:
  httpd:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - "./config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"

  registry:
    image: registry:2
    ports:
      - "5000"
    volumes:
      - "./data/registry:/var/lib/registry"
    healthcheck:
      test: ["CMD", "wget", "-s", "localhost:5000/v2/"]
      interval: 5s
      timeout: 10s

  registry-ui:
    image: quiq/docker-registry-ui:latest
    ports:
      - "8000"
    volumes:
      - "./data/registry-ui:/opt/data"
      - "./config/registry-ui.yml:/opt/config.yml:ro"
    depends_on:
      registry:
        condition: service_healthy
